### ISSUE TITLE
Install geokit by docker

### ISSUE THREAD

**Issue by Rub21** [developmentseed/ayp-doc-seed#10]
![image](https://user-images.githubusercontent.com/1152236/46765066-b39dd100-cca3-11e8-9a28-46d0816813be.png)
cc. @piligab @karitotp

**Comment by piligab** [comment]
I changed the steps for the installation :point_up: 
![image](https://user-images.githubusercontent.com/19536044/47047307-d1b07900-d15c-11e8-927c-0a7b4aad0cbc.png)

@Rub21 when we will add geokit to hub the installation will change?

cc. @karitotp

**Comment by karitotp** [comment]
This is done!
